version: "3.9"
services:
  app:
build: .
    image: hameed1983/app:v2
    environment:
- FLASK_ENV=development
    ports:
- "5000:5000"
    networks:
- flasnet

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
- "6379:6379"
    networks:
- flasnet

networks:
  flasnet:
    driver: bridge
